name: deploy-container

on:
  push:
    branches:
      - master

defaults:
  run:
    working-directory: packages/container

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build
        env:
          PRODUCT_DOMAIN: ${{ secrets.PRODUCT_DOMAIN }}

      - name: Login to azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Application
        uses: actions/checkout@v2
        uses: chabad360/hugo-actions@master
        uses: bacongobbler/azure-blob-storage-upload@v1.2.0
        with:
          source_dir: "dist"
          container_name: "container"
          connection_string: ${{ secrets.AZURE_CREDENTIALS }}
          sync: true
